travis:
  secure:
    BINSTAR_TOKEN: wtUeLubKTSbT593J3L/O0YjY4XDbAtuf26iRF3iXGZAvnZZolenpB04t7ieq/5NjZ51rKeNQooIlF/eQDEY4BYU58qspJPeI58elGcEgGL+zkJakEAKgYZW1neXJrq/MJSgr34H4+Gesr87mF17rMNQ9w+VgJ/+Id988sy2sB08EEWdt88jQ8/arBsH6U3wiFw5oqULIcGHeWu2wjFkvcrRkFbpYyMCqIIWv57WXiNWMyOqYqHY1GmGZYTfdHXji6LGN27xN4COj5eEF3jwx0jblgamop6rnc9xG4WCATzPxo8UhdzIGUocjpd3+6XOJgnCm5Y2CIeV+GK2bDZyE4ezevp5/yeqpArNpRgf119gGhE1RvIBCbYl1EJRUCqyi1kYFsjl/VsD2yRTvQ/XIC2jQ+YWErzQijvRL+I/tp87wS+6NgIsjfidCw9e32HX5OFkwz6g3NjFqv+iypQLx0gPbb1LdTpwG402zAnJZ/DZuNHqpqhXCVzd9nSxKo2e1zz/zdxvqu4ezVKCDCpHZ2n8+FqtSeVxoRUBDefff1XQWA0la3TVRf1BxLQ0F1B5cg8bw4v8ufsl3KS4T9XOZ60zmXw5wO/zk2QaF5WGQUBwjsQbjASpuD+rqCX8fTlkOJ9zXH/Uirc37WFgl4CzmmSsl04IAr34WKoOiYhn1nDc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
